# Travis CI for compiling Atmel Studio 7 Solution
# -----------------------------------------------
language: c
sudo: false

# Dependencies
addons:
  apt:
    packages:
      - binutils-avr
      - avr-libc
      - gcc-avr

install:
  - avr-gcc --version
  - make --version

# Execute Commands bevor Build
before_script:
  - mkdir module
  - find . -maxdepth 1 ! -name module ! -name . -exec mv "{}" target /module;
  - chmod 0777 scripts/CI/makefile2unix.sh
  - scripts/CI/makefile2unix.sh module/MAX7219/
  - git clone https://github.com/sunriax/STK500.git

# Run Build Script
script:
  - cd module/MAX7219/Debug
  - mkdir src
  - make
  - cd ../../
