# Travis CI for compiling Atmel Studio 7 Solution
# -----------------------------------------------
language: c
sudo: false

# Dependencies
addons:
  apt:
    packages:
      - binutils-avr
      - avr-libc
      - gcc-avr
      - git

install:
  - avr-gcc --version
  - make --version

# Execute Commands bevor Build
before_script:
  - chmod 0777 scripts/CI/makefile2unix.sh
  - scripts/CI/makefile2unix.sh MAX7219/
  - git clone https://github.com/sunriax/STK500.git
  - cp STK500/spi/spi.h ./
  - cp STK500/spi/spi.c ./


# Run Build Script
script:
  - cd MAX7219/Debug
  - mkdir src
  - make
  - cd ../../
